"""created amenities table

Revision ID: 20fbc69f889b
Revises: 9e13261c104f
Create Date: 2023-11-28 12:02:32.355313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20fbc69f889b'
down_revision = '9e13261c104f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amenity_items', sa.String(), nullable=True),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('neighborhood_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], name=op.f('fk_amenities_neighborhood_id_neighborhoods')),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_amenities_park_id_parks')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amenities')
    # ### end Alembic commands ###
