"""new domain model

Revision ID: ad7fc16513bd
Revises: 20fbc69f889b
Create Date: 2023-11-29 20:24:16.999126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7fc16513bd'
down_revision = '20fbc69f889b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_amenities_neighborhood_id_neighborhoods', type_='foreignkey')
        batch_op.drop_constraint('fk_amenities_park_id_parks', type_='foreignkey')
        batch_op.drop_column('neighborhood_id')
        batch_op.drop_column('park_id')

    with op.batch_alter_table('parks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amenity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('neighborhood_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_parks_amenity_id_amenities'), 'amenities', ['amenity_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_parks_neighborhood_id_neighborhoods'), 'neighborhoods', ['neighborhood_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_parks_neighborhood_id_neighborhoods'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_parks_amenity_id_amenities'), type_='foreignkey')
        batch_op.drop_column('neighborhood_id')
        batch_op.drop_column('amenity_id')

    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('park_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('neighborhood_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_amenities_park_id_parks', 'parks', ['park_id'], ['id'])
        batch_op.create_foreign_key('fk_amenities_neighborhood_id_neighborhoods', 'neighborhoods', ['neighborhood_id'], ['id'])

    # ### end Alembic commands ###
